#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# Pre-requisite: run ./build.sh from this directory to populate build-target/.
FROM eclipse-temurin:17-jre-noble

RUN set -ex; \
    apt-get update; \
    apt-get -y install gettext-base libsnappy1v5 libjemalloc-dev; \
    rm -rf /var/lib/apt/lists/*

ENV FLUSS_HOME=/opt/fluss
ENV PATH=$FLUSS_HOME/bin:$PATH

RUN groupadd --system --gid=9999 fluss && \
    useradd --system --home-dir $FLUSS_HOME --uid=9999 --gid=fluss fluss

WORKDIR $FLUSS_HOME

COPY --chown=fluss:fluss build-target/ /opt/fluss/
COPY --chown=fluss:fluss conf/ /opt/fluss/conf/
COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh

USER fluss
EXPOSE 9122 9123 9092 8081

ENTRYPOINT ["/entrypoint.sh"]
CMD ["help"]
